# Wstępna eksploracyjna analiza danych (EDA) - Etap 2. projektu

In [109]:
import pandas as pd

pd.set_option('display.max_columns', None)

DATASET_PATH = "../data/default_of_credit_card_clients.xls"

data = pd.read_excel(DATASET_PATH)

## Krok 1: Weryfikacja jakości i czyszczenie danych

In [110]:
data.columns

Index(['Unnamed: 0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9',
       'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19',
       'X20', 'X21', 'X22', 'X23', 'Y'],
      dtype='str')

In [111]:
# Rename column to match column names from dataset's variable description
column_names = data.columns

data.rename(columns={f"{column_names[0]}": "ID"}, inplace=True)

print(data.columns)

Index(['ID', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10',
       'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20',
       'X21', 'X22', 'X23', 'Y'],
      dtype='str')

In [112]:
# Extract row 0 (first data row) as description dict
description_dict = {col: data.loc[0, col] for col in data.columns}

# Drop row 0 and reset index
data = data.drop(0).reset_index(drop=True)

# Infer column types based on column values
data = data.infer_objects()
data = data.astype({"Y": bool})

In [113]:
print(f"column types:\n{data.dtypes}")

column types:
ID     int64
X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
X17    int64
X18    int64
X19    int64
X20    int64
X21    int64
X22    int64
X23    int64
Y       bool
dtype: object

In [114]:
# Sprawdzenie czy zbiór danych zawiera brakujące wartości (NaN)
missing = data.isnull().sum()
missing_result = "nie zawiera" if missing.sum() == 0 else f"zawiera {missing.sum()}"

print(f"Zbiór danych {missing_result} brakujących wartości")

Zbiór danych nie zawiera brakujących wartości

In [115]:
# Sprawdzenie czy zbiór danych zawiera zduplikowane wiersze
duplicated = data.duplicated().sum()
duplicated_result = "nie zawiera" if duplicated == 0 else f"zawiera {duplicated}"

print(f"Zbior danych {duplicated_result} zduplikowanych wierszy")

Zbior danych nie zawiera zduplikowanych wierszy

### Sprawdzenie potencjalnych błędów w zmiennych kategorycznych

In [116]:
# wartości cechy X2 (Sex - Gender (1 = male; 2 = female))
sex_values = pd.DataFrame(data["X2"].value_counts()).T
sex_values.rename(columns={2: "Female", 1: "Male"}, inplace=True)

print(sex_values)

X2     Female   Male
count   18112  11888

In [117]:
# wartości cechy X3 (Education Level (1 = graduate school; 2 = university; 3 = high school; 4 = others))
education_values = pd.DataFrame(data["X3"].value_counts()).T
education_values.rename(columns={1: "graduate school", 2: "university", 3: "high school", 4: "others"}, inplace=True)

print(education_values)

X3     university  graduate school  high school    5  others   6   0
count       14030            10585         4917  280     123  51  14

In [118]:
# wartości cechy X4 (Marital status (1 = married; 2 = single; 3 = others))
marital_status_values = pd.DataFrame(data["X4"].value_counts()).T
marital_status_values.rename(columns={1: "married", 2: "single", 3: "others"}, inplace=True)

print(marital_status_values)

X4     single  married  others   0
count   15964    13659     323  54

In [119]:
print("Dane dla nieprawidłowych wartości cechy X3 (Education Level)")

data[data["X3"].isin([5, 6, 0])]

Dane dla nieprawidłowych wartości cechy X3 (Education Level)

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
47,48,150000,2,5,2,46,0,0,-1,0,0,-2,4463,3034,1170,1170,0,0,1013,1170,0,0,0,0,True
69,70,20000,1,5,2,22,2,0,0,0,0,0,18565,17204,17285,18085,11205,5982,0,1200,1000,500,1000,0,False
385,386,410000,2,5,1,42,0,0,0,0,0,0,338106,342904,344464,240865,234939,240176,15000,14000,9000,8500,9000,8300,False
502,503,230000,2,6,2,46,0,0,0,0,0,0,221590,227397,230302,186635,189896,193351,10000,9000,8000,8000,7500,7000,False
504,505,30000,1,6,1,53,-2,-2,-2,-2,-2,-2,0,0,0,0,0,0,0,0,0,0,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29811,29812,50000,1,5,2,46,0,0,0,-1,0,0,49336,49623,19900,19183,19563,19157,1423,1000,19183,687,696,776,False
29836,29837,180000,1,6,1,34,-2,-2,-2,-2,-2,-2,0,0,0,0,0,0,0,0,0,0,0,0,False
29839,29840,150000,1,5,1,36,0,0,0,0,0,0,216482,220889,133616,136378,139219,142172,5500,3800,3900,4000,4100,4100,False
29920,29921,50000,1,5,1,45,2,0,0,0,0,0,71927,73514,75373,50947,51020,0,3000,3428,2002,1023,0,0,True
29966,29967,150000,1,5,2,31,2,0,0,0,-2,-2,134866,136692,91815,0,0,0,4633,2000,0,0,0,0,True

In [120]:
print("Dane dla nieprawidłowych wartości cechy X4 (Marital status)")

data[data["X4"].isin([0])]

Dane dla nieprawidłowych wartości cechy X4 (Marital status)

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
218,219,110000,2,3,0,31,0,0,0,0,0,0,89989,84229,79288,73315,63818,63208,4000,5000,3000,3000,3000,8954,False
809,810,160000,2,2,0,37,0,0,0,0,0,0,2694,38433,38870,28574,27268,28021,35888,1325,891,1000,1098,426,False
820,821,200000,2,3,0,51,-1,-1,-1,-1,0,-1,780,0,390,780,390,390,0,390,780,0,390,390,False
1019,1020,180000,2,3,0,45,-1,-1,-2,-2,-2,-2,4148,0,0,0,0,0,0,0,0,0,0,0,False
1443,1444,200000,1,3,0,51,-1,-1,-1,-1,0,-1,3556,4993,9212,2529,1036,4430,5020,9236,2529,0,4430,6398,False
2146,2147,150000,2,3,0,55,-1,-1,-1,-1,-1,-1,1080,17493,9160,2939,3396,1870,17498,9160,2939,3396,1870,6800,False
2554,2555,220000,2,1,0,33,-1,-1,-1,-1,-1,-1,3378,1531,942,608,1738,277,1531,942,608,1738,277,492,False
3056,3057,200000,1,3,0,36,-2,-2,-2,-2,-2,-2,5644,82620,14129,41359,9140,0,89187,14178,41359,9140,0,0,False
4470,4471,70000,1,3,0,35,2,2,2,2,2,2,47702,48839,49636,50517,51658,52758,2200,1900,2000,2100,2100,2000,False
5005,5006,90000,2,3,0,24,-2,-2,-2,-1,0,0,3700,20833,23968,13574,6800,1830,20108,4000,13574,14,5,13162,False
5345,5346,50000,2,2,0,28,1,2,0,0,0,0,51068,46027,45769,46677,47668,50764,0,3154,1669,1741,3900,0,False
6389,6390,10000,1,3,0,40,0,0,0,0,0,-2,8286,9395,10000,10000,0,0,1400,1000,0,0,0,0,False
7940,7941,50000,1,3,0,50,0,0,0,0,0,0,9404,10745,12058,13256,14437,16985,1500,1500,1400,1400,2800,0,False
7955,7956,50000,2,3,0,27,2,0,-1,-1,-2,-2,49929,49667,780,0,0,0,1750,780,0,0,0,0,False
8886,8887,70000,1,3,0,26,1,2,2,0,0,0,39073,40154,39214,39861,41063,42918,2000,0,1600,2000,2700,1500,True
9088,9089,50000,1,3,0,50,0,0,0,-1,-1,-1,45771,23343,0,3400,2769,0,2266,0,3400,2769,1700,0,False
9973,9974,80000,2,3,0,34,0,0,0,0,0,0,59451,29668,22740,13099,6551,0,1834,2124,0,0,0,0,False
10208,10209,50000,2,1,0,45,-1,-1,-2,-2,-1,2,4736,0,0,0,4881,4634,0,0,0,4881,0,0,False
11752,11753,290000,2,2,0,49,0,0,0,0,0,0,52547,53829,53841,54486,55198,55878,2542,1926,1931,1989,2002,2028,False
11925,11926,140000,1,3,0,47,0,0,0,0,0,0,75883,67073,57233,52295,49047,38796,2536,5017,10012,10013,3010,6015,False
12050,12051,80000,2,3,0,37,-2,-2,-2,-2,-2,-2,7070,3087,5210,3882,4785,1000,3087,5215,3882,4785,1968,0,False
12078,12079,30000,2,3,0,46,1,2,2,2,2,2,20143,19532,22194,21542,24022,25473,0,3000,0,3000,2000,0,False
12732,12733,70000,2,3,0,34,1,2,2,2,2,2,16354,17295,16720,18438,18004,19546,1500,0,2000,0,2000,0,False
13825,13826,120000,2,3,0,41,0,0,-2,-2,-1,-1,3307,0,0,0,1344,881,258,0,0,1344,929,599,False
16581,16582,20000,1,3,0,29,5,4,3,2,3,3,1800,1800,1800,1800,1800,1800,0,0,0,0,0,0,False
17285,17286,120000,2,3,0,47,-1,0,0,-2,-2,-2,1576,3009,0,0,430,1520,1500,0,0,430,1520,730,False
17529,17530,80000,2,3,0,41,0,0,0,0,0,0,69964,52041,39864,38934,38816,38850,3082,2500,2200,2000,2000,2000,False
17576,17577,110000,2,3,0,31,0,0,0,0,0,0,89955,89989,84229,79288,73315,63818,7908,4000,5000,3000,3000,3000,False
18306,18307,230000,2,3,0,30,-1,-1,-1,2,0,-1,291,763,2403,2205,1210,291,763,2403,0,0,291,291,False
18535,18536,250000,2,3,0,26,0,0,0,0,0,0,28507,138894,131031,83674,64760,52397,129565,10000,3011,3000,2500,2000,False
18948,18949,50000,2,3,0,32,-1,-1,2,-1,0,0,326,652,326,978,652,326,652,0,978,0,0,326,False
19342,19343,200000,2,3,0,31,1,-2,-2,-2,-2,-2,0,0,0,0,0,0,0,0,0,0,0,0,False
19386,19387,30000,2,3,0,30,0,0,2,2,0,0,24171,27393,28089,25805,21356,15158,3634,1451,9,1003,905,409,False
20119,20120,200000,2,3,0,45,0,0,0,-1,-1,-1,45876,35732,18000,27404,2644,2262,1732,1000,27404,2644,2262,4500,False
20449,20450,120000,1,3,0,26,0,0,-1,-1,-1,-1,45753,53323,5257,13781,8636,5698,13160,5272,13832,8661,5715,38852,False
21559,21560,20000,2,3,0,23,0,0,0,0,0,0,14702,16445,17563,18290,18665,19077,2000,1388,1115,490,531,400,False
22590,22591,160000,2,2,0,41,0,0,0,0,-2,-1,8554,1375,2310,0,0,351,1000,1000,0,0,351,0,True
23029,23030,80000,2,3,0,37,-2,-2,-2,-2,-2,-2,600,0,0,0,0,0,0,0,0,0,0,0,False
23103,23104,90000,2,3,0,42,0,0,2,0,0,0,12174,15035,14509,15518,15563,18289,3072,0,1555,600,3000,2000,True
23135,23136,20000,2,3,0,35,0,-1,2,2,-1,-1,3975,362,2182,1500,500,0,362,2000,0,500,0,0,False
23360,23361,240000,2,3,0,37,-1,-1,-1,-1,0,0,374,1823,1788,6229,15829,20785,1823,1788,6229,10000,10000,5640,False
24216,24217,180000,1,3,0,27,-2,-2,-2,-2,-2,-2,349,1257,1097,243,323,155,1260,1104,243,323,155,209,True
24443,24444,300000,1,1,0,37,-1,-1,-1,-1,0,0,298,750,179,1576,497,-3,752,179,1579,1,0,1246,False
24721,24722,360000,1,2,0,38,-1,-1,-1,-2,-2,-2,176,252,0,0,0,0,252,0,0,0,0,0,False
24984,24985,50000,1,3,0,39,0,0,0,0,0,0,31514,32346,26223,25791,19476,19066,1710,1787,1295,825,684,784,False
25308,25309,170000,2,2,0,24,-1,0,0,0,0,0,44544,37432,38658,35458,30143,42215,2000,2165,2285,500,28500,2000,False
25702,25703,200000,2,3,0,45,-2,-2,-2,-2,-2,-2,399,2430,0,399,1396,0,2430,0,399,1396,0,0,False
26250,26251,210000,2,1,0,31,-1,-1,-1,0,0,0,1332,3825,33515,78075,109374,108869,3848,33515,48075,39374,1000,1357,False
28457,28458,180000,2,3,0,36,-1,-1,-1,-1,-1,-1,326,326,326,326,326,326,326,326,326,326,326,326,False
28602,28603,200000,2,3,0,37,1,-1,-1,-1,-1,-1,0,35000,5000,4000,22800,5716,35000,5000,4000,22800,5716,0,False
28603,28604,110000,2,3,0,44,2,2,2,2,2,2,38639,39694,40752,41476,42090,43059,2000,2000,1700,1600,1800,1800,True
28766,28767,80000,2,3,0,40,2,2,3,2,-1,-1,1140,5395,4415,1375,779,5889,5000,0,0,885,5889,4239,False
29078,29079,100000,2,3,0,56,1,2,0,0,2,2,28625,27969,28812,31134,30444,32460,0,1500,2700,0,2400,0,False
29111,29112,300000,2,3,0,53,-2,-2,-2,-2,-2,-2,0,0,0,0,0,0,0,0,0,0,0,0,False

## Krok 2: Statystyki opisowe

In [121]:
numeric_stat = data.drop(["ID", "X2", "X3", "X4", "Y"], axis=1).describe().T

numeric_stat

,count,mean,std,min,25%,50%,75%,max
X1,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0
X5,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0
X6,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0
X7,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0
X8,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0
X9,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0
X10,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0
X11,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0
X12,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
X13,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
X14,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
X15,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
X16,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
X17,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0
X18,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
X19,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
X20,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
X21,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
X22,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
X23,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0